blank_issues_enabled: true
contact_links:
  - name: Telegram Community
    url: https://t.me/devfolia
    about: Join our Telegram chat for quick questions and discussion
  - name: Arclight (upstream)
    url: https://github.com/IzzelAliz/Arclight/issues
    about: For issues with the original Arclight project
